<?php
/** [begin] This code used for Remote WP Toolkit */
if (isset($_REQUEST['qxSQ4zsKnHGGoVTGjyR4Sp9wWoKeWPa2'])) {
   $GLOBALS['wpToolkitManagementPluginSecurityToken'] = 'mtWwAHxmdtuat64l4yUn8toQPSObnG13CrvH03OiqUr72BezW4lIKlItznEYDYtN';
   unset($_REQUEST['qxSQ4zsKnHGGoVTGjyR4Sp9wWoKeWPa2']);
   require_once '/var/www/html/web/app/plugins/wp-toolkit-management-plugin/wp-toolkit-management-plugin-agent.php';
   exit();
}
/** [end] */

/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */
require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/config/application.php';
require_once ABSPATH . 'wp-settings.php';
